import os
import cv2
import time
import argparse
import numpy as np

ap = argparse.ArgumentParser()
ap.add_argument("-i", "--image", type=str,
    default="HICO_test2015_00000001.jpg",
    help="path to input image that we'll apply GrabCut to")
ap.add_argument("-c", "--iter", type=int, default=10,
    help="# of GrabCut iterations (larger value => slower runtime)")

ap = ap.parse_args()

# load image and create mask for output generated by GrabCut
image = cv2.imread(ap.image)
mask = np.zeros(image.shape[:2], dtype="uint8")

# define boudngin box coordinates
rect = (300, 300, 350, 350)

fgModel = np.zeros((1, 65), dtype="float")
bgModel = np.zeros((1, 65), dtype="float")

# apply GrabCut 
(mask, fgModel, bgModel) = cv2.grabCut(image, mask, rect, bgModel, fgModel, iterCount=ap.iter, mode=cv2.GC_INIT_WITH_RECT)

values = (
    ("Definite Background", cv2.GC_BGD),
    ("Probable Background", cv2.GC_PR_BGD),
    ("Definite Foreground", cv2.GC_FGD),
    ("Probable Foreground", cv2.GC_PR_FGD),
)

for (name, value)  in values:
    valueMask = (mask==value).astype("uint8")*255
    cv2.imwrite(name+".jpg", valueMask)
   
